FROM python:3.9-bullseye
# TODO: try python 3.11

RUN apt update -y
RUN apt install -y libopencv-dev

COPY requirements.txt .

RUN pip install --upgrade pip

# RUN pip install opencv-python

RUN pip install -r requirements.txt

COPY . ./

RUN pip install .
